# Generated by Django 5.2.12 on 2026-05-19 16:56

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0056_gfk_indexes'),
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_prefixes', to='circuits.circuit')),
                ('prefix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_link', to='ipam.prefix')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Circuit-Prefix Link',
                'verbose_name_plural': 'Circuit-Prefix Links',
                'ordering': ('circuit', 'prefix'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
